this.linkLookups
this.linkLookupSearch
this.txtLookupCode
this.txtLookupName
this.btnSearch
this.tableValue
this.btnClear
this.lookupCodecleared
this.lookupNamecleared
this.btnActions
this.btnNew
this.txtLVLookupCode
this.txtLVLookupName
this.txtKey1Label
this.txtKey2Label
this.txtKey3Label
this.txtKey4Label
this.txtKey5Label
this.txtValue1Label
this.txtValue2Label
this.txtValue3Label
this.txtValue4Label
this.txtValue5Label
this.btnUpdate
this.btnView        
this.btnDelete 
this.tableValueView
this.btnView     
this.btnNewLookupValue        
this.txtKey1
this.txtKey2
this.txtKey3
this.txtKey4
this.txtKey5
this.txtValue1
this.txtValue2
this.txtValue3
this.txtValue4
this.txtValue5
this.btnUpdate1
this.btnView1
this.btnDelete1
this.btnDownloadCSV 
this.btnView    
this.btnUploadCSV
